// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using luafalcao.api.Persistence.Models;

namespace luafalcao.api.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220821172433_CriandoBancoDeDados")]
    partial class CriandoBancoDeDados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("luafalcao.api.Persistence.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "21974737578",
                            Cpf = "222222222222",
                            Nome = "John Doe",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = 2,
                            Celular = "21999999999",
                            Cpf = "53751655115",
                            Nome = "Jaina Proudmore",
                            UF = "SP"
                        },
                        new
                        {
                            Id = 3,
                            Celular = "21999999999",
                            Cpf = "44831876941",
                            Nome = "Arthas",
                            UF = "SP"
                        });
                });

            modelBuilder.Entity("luafalcao.api.Persistence.Models.Financiamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FinanciamentoId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUltimoVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinanciamentoTipoId")
                        .HasColumnType("int");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FinanciamentoTipoId")
                        .IsUnique();

                    b.ToTable("Financiamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            DataUltimoVencimento = new DateTime(2022, 9, 10, 14, 24, 33, 307, DateTimeKind.Local).AddTicks(3029),
                            FinanciamentoTipoId = 1,
                            ValorTotal = 35000.949999999997
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            DataUltimoVencimento = new DateTime(2022, 9, 10, 14, 24, 33, 309, DateTimeKind.Local).AddTicks(1752),
                            FinanciamentoTipoId = 2,
                            ValorTotal = 4000.0
                        });
                });

            modelBuilder.Entity("luafalcao.api.Persistence.Models.FinanciamentoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FinanciamentoId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinanciamentoTipo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "SFH"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "SFI"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "SAC"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Sacre"
                        });
                });

            modelBuilder.Entity("luafalcao.api.Persistence.Models.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ParcelaId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinanciamentoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<double>("ValorParcela")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FinanciamentoId");

                    b.ToTable("Parcelas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataPagamento = new DateTime(2022, 8, 31, 14, 24, 33, 310, DateTimeKind.Local).AddTicks(6083),
                            DataVencimento = new DateTime(2022, 9, 21, 14, 24, 33, 312, DateTimeKind.Local).AddTicks(8121),
                            FinanciamentoId = 1,
                            NumeroParcela = 20,
                            ValorParcela = 500.0
                        },
                        new
                        {
                            Id = 2,
                            DataPagamento = new DateTime(2022, 8, 31, 14, 24, 33, 312, DateTimeKind.Local).AddTicks(9928),
                            DataVencimento = new DateTime(2022, 9, 21, 14, 24, 33, 312, DateTimeKind.Local).AddTicks(9950),
                            FinanciamentoId = 2,
                            NumeroParcela = 15,
                            ValorParcela = 255.25
                        },
                        new
                        {
                            Id = 3,
                            DataVencimento = new DateTime(2022, 9, 21, 14, 24, 33, 313, DateTimeKind.Local).AddTicks(14),
                            FinanciamentoId = 2,
                            NumeroParcela = 15,
                            ValorParcela = 255.25
                        },
                        new
                        {
                            Id = 4,
                            DataVencimento = new DateTime(2022, 10, 21, 14, 24, 33, 313, DateTimeKind.Local).AddTicks(17),
                            FinanciamentoId = 2,
                            NumeroParcela = 30,
                            ValorParcela = 2500.25
                        });
                });

            modelBuilder.Entity("luafalcao.api.Persistence.Models.Financiamento", b =>
                {
                    b.HasOne("luafalcao.api.Persistence.Models.Cliente", "Cliente")
                        .WithMany("Financiamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("luafalcao.api.Persistence.Models.FinanciamentoTipo", "FinanciamentoTipo")
                        .WithOne("Financiamento")
                        .HasForeignKey("luafalcao.api.Persistence.Models.Financiamento", "FinanciamentoTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("luafalcao.api.Persistence.Models.Parcela", b =>
                {
                    b.HasOne("luafalcao.api.Persistence.Models.Financiamento", "Financiamento")
                        .WithMany()
                        .HasForeignKey("FinanciamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
